/**
 * v2.2 parity against the REAL wrapper crate (percolator-prog release/v22-wrapper-rem c8501d15 on engine
 * release/v22-engine-rem b0634da5). Fixture: test/fixtures/v22-parity.json, generated by
 * scripts/v22-parity/sdk_v22_parity.rs (see its header). Every encoder has a golden vector decoded AND re-encoded by
 * the real `ix::Instruction`, plus mutation negative controls.
 */
import { readFileSync } from "node:fs";
import { PublicKey } from "@solana/web3.js";
import { describe, expect, it } from "vitest";
import { V22_REFUSED, V22_VECTORS } from "./v22-vector-inputs.js";
import { P2B_INIT_MARKET_ARGS } from "./p2b-vector-inputs.js";
import * as W from "../src/abi/v22-wire.js";
import * as S from "../src/abi/v22-state.js";
import * as M from "../src/abi/v22-math.js";
import { LAYOUT_V21, LAYOUT_V22, LAYOUT_V22_STAGE_A, LAYOUT_V22_VARIANT_B, UnknownLayoutError } from "../src/abi/layout.js";
import { PERCOLATOR_ERRORS } from "../src/abi/errors.js";

interface Rule { fn: string; in: string[]; out: (string | null)[] }
const FX = JSON.parse(readFileSync(new URL("./fixtures/v22-parity.json", import.meta.url), "utf8")) as {
  prog: string; vectors: Record<string, { hex: string; rust: { ok: boolean; decoded?: Record<string, unknown>; err?: string }; rustReencodedHex: string }>;
  errors: Record<string, number>; layout: Record<string, any>; constants: Record<string, any>; accounts: Record<string, any>; rules: Rule[];
  pdas: any[]; g9Pda: { pda: string; bump: number };
};
const hex = (b: Uint8Array) => Buffer.from(b).toString("hex");
const unhex = (s: string) => Uint8Array.from(Buffer.from(s, "hex"));

describe("pinned oracle", () => {
  it("is variant B", () => expect(FX.prog).toBe("c8501d153ed1a7bd9b1bc3343b89f47096838ead"));
});

describe("instruction golden vectors (encoder == real decoder; real re-encode == SDK bytes)", () => {
  for (const [id, v] of Object.entries(V22_VECTORS)) {
    it(id, () => {
      const bytes = v.build();
      const f = FX.vectors[id];
      expect(hex(bytes), "SDK bytes drifted from the fixture").toBe(f.hex);
      expect(f.rust.ok, `real decoder refused ${id}: ${f.rust.err}`).toBe(true);
      expect(f.rust.decoded).toMatchObject({ variant: v.variant, tag: v.tag, ...v.fields });
      expect(f.rustReencodedHex).toBe(f.hex);
      expect(bytes[0]).toBe(v.tag);
    });
    it(`${id}: short and long payloads`, () => {
      const f = FX.vectors[`${id}__short`];
      const l = FX.vectors[`${id}__long`];
      if (v.tag === 0) {
        // the InitMarket trailer is LENGTH-selected: a one-byte change can land on another valid form
        const okLens = new Set([4, 5, 10, 11, 28, 29]);
        const trailer = v.build().length - 219;
        if (!okLens.has(trailer - 1)) expect(f.rust.ok, "short").toBe(false);
        if (!okLens.has(trailer + 1)) expect(l.rust.ok, "long").toBe(false);
      } else {
        if (f) expect(f.rust.ok, "short").toBe(false);
        expect(l.rust.ok, "long").toBe(false);
      }
    });
    it(`${id}: NEGATIVE CONTROL: any mutated byte breaks the vector check`, () => {
      const good = FX.vectors[id].hex;
      const bytes = v.build();
      for (let i = 0; i < bytes.length; i++) {
        const m = Uint8Array.from(bytes); m[i] ^= 0x01;
        expect(hex(m), `mutating byte ${i} must not match`).not.toBe(good);
      }
    });
  }
  it("NEGATIVE CONTROL: swapping two fields changes the bytes (min_payout vs shares in tag 76)", () => {
    const a = W.encodeRequestRedeemLpSharesV22({ shares: 0x1122334455667788n, minPayoutAtoms: 5n, keeperOk: true });
    const b = W.encodeRequestRedeemLpSharesV22({ shares: 5n, minPayoutAtoms: 0x1122334455667788n, keeperOk: true });
    expect(hex(a)).not.toBe(hex(b));
    expect(hex(a)).not.toBe(FX.vectors.request76.hex);
  });
  for (const id of Object.keys(V22_REFUSED)) {
    it(`refused by the real decoder: ${id}`, () => expect(FX.vectors[`refused_${id}`].rust.ok).toBe(false));
  }
  it("the SDK refuses what the real decoder refuses", () => {
    const base = P2B_INIT_MARKET_ARGS;
    expect(() => W.encodeInitMarketV22(base, { rGapBps: 4, lLaunchX100: 5, lotExp: 0 })).toThrow(/lotExp 0/);
    expect(() => W.encodeInitMarketV22(base, { rGapBps: 4, lLaunchX100: 5, band: { ...W.bandDefaultsV22(6) } })).toThrow(/requires the rent/);
    expect(() => W.encodeInitMarketV22(base, { rGapBps: 0, lLaunchX100: 5 })).toThrow(/rGapBps 0/);
    expect(() => W.encodeInitMarketV22(base, { rGapBps: 4, lLaunchX100: 0 })).toThrow();
    expect(() => W.encodeRequestRedeemLpSharesV22({ shares: 1n, minPayoutAtoms: 0n, keeperOk: true })).toThrow();
    expect(() => W.encodeExecuteRedemptionV22({ domain: 1, minPayoutAtoms: 0n, nRefresh: 0 })).toThrow(/all-zero/);
    expect(() => W.encodeExecuteRedemptionV22({ domain: 1, minPayoutAtoms: 1n, nRefresh: 9 })).toThrow();
    expect(() => W.encodeSetG9FeedAllowlistV22(Array.from({ length: 17 }, (_, i) => new PublicKey(new Uint8Array(32).fill(i + 1))))).toThrow();
    expect(() => W.encodeInitBondTrancheV22({ couponBps: 801, utilBonusBps: 1, cooldownSlots: 9000, capBps: 10 })).toThrow();
  });
  it("band / rent floors mirror the engine", () => {
    expect(() => W.assertBandBlockV22({ ...W.bandDefaultsV22(6), bandMaxEpochSlots: 149 })).toThrow();
    expect(() => W.assertBandBlockV22({ ...W.bandDefaultsV22(6), bandMaxPinSlots: 600 * 8 - 1 })).toThrow();
    expect(() => W.assertBandBlockV22(W.bandDefaultsV22(6), 6)).not.toThrow();
    expect(() => W.assertBandBlockV22({ ...W.bandDefaultsV22(6), bandMinLegNotional: 9_999_999n }, 6)).toThrow();
    expect(() => W.assertRentBlockV22({ rentMaxE9PerSlot: 9, rentKinkBps: 0 })).toThrow();
    expect(() => W.assertRentBlockV22({ rentMaxE9PerSlot: 10, rentKinkBps: 8001 })).toThrow();
    expect(W.bandDefaultsV22(6)).toEqual({ bandBps: 130, bandMaxEpochSlots: 600, bandMaxPinSlots: 9000, bandMinLegNotional: 100_000_000n });
    expect(W.forcedRecoveryMinutesV22(W.bandDefaultsV22(6))).toBeCloseTo(64, 0);
  });
});

describe("constants, errors, tags", () => {
  const C = FX.constants;
  it("constants equal the crate's", () => {
    expect([W.REDEMPTION_REFRESH_MAX_V22, W.REDEMPTION_REFRESH_BASE_WEIGHT_V22, W.REDEMPTION_REFRESH_WEIGHT_BUDGET_V22, W.EXIT_DIP_BPS_V22]).toEqual([C.refreshMax, C.refreshBaseWeight, C.refreshWeightBudget, C.exitDipBps]);
    expect([W.LOT_EXP_MAX_V22, Number(W.LOT_PRICE_FLOOR_E6_V22)]).toEqual([C.lotExpMax, C.lotPriceFloorE6]);
    expect([W.BOND_COUPON_MAX_BPS_V22, W.BOND_UTIL_BONUS_MAX_BPS_V22, W.BOND_COOLDOWN_MIN_SLOTS_V22, W.BOND_COOLDOWN_MAX_SLOTS_V22, W.BOND_CAP_MAX_BPS_V22, W.BOND_COUPON_MAX_LEG_BPS_V22, Number(W.SLOTS_PER_YEAR_V22)])
      .toEqual([C.bondCouponMaxBps, C.bondUtilBonusMaxBps, C.bondCooldownMin, C.bondCooldownMax, C.bondCapMaxBps, C.bondCouponMaxLegBps, C.slotsPerYear]);
    expect([W.RESCUE_NAV_FLOOR_BPS_V22, Number(W.RESCUE_MIN_ATOMS_V22), Number(W.RESCUE_MAX_MULT_V22), Number(W.INS_UNITS_GENESIS_MIN_ATOMS_V22), W.BACKSTOP_CAP_BPS_V22, Number(W.G9_DELAY_SLOTS_V22), Number(W.G9_EXEC_WINDOW_SLOTS_V22), Number(W.G9_EPOCH_SLOTS_V22), W.G9_EPOCH_CAP_BPS_V22, W.RESTORE_IM_BUFFER_BPS_V22, W.G9_FEED_ALLOWLIST_CAP_V22])
      .toEqual([C.rescueNavFloorBps, C.rescueMinAtoms, C.rescueMaxMult, C.insUnitsGenesisMin, C.backstopCapBps, C.g9Delay, C.g9ExecWindow, C.g9EpochSlots, C.g9EpochCapBps, C.restoreImBufferBps, C.g9FeedCap]);
    expect([W.P4_FLAG_INS_UNITS_REQUIRED_V22, W.P4_FLAG_EXIT_REQUIRES_LOSS_CURRENT_V22]).toEqual([C.p4InsUnitsRequired, C.p4ExitRequiresLossCurrent]);
    expect([W.MAX_BAND_BPS_V22, W.BAND_MIN_EPOCH_SLOTS_V22, W.BAND_MIN_PIN_EPOCHS_V22, W.BAND_MAX_POSITIONS_PER_SIDE_V22, W.MIN_BAND_WIDTH_TICKS_V22, W.BAND_GENESIS_FLOOR_MULTIPLE_V22, W.MAX_RENT_E9_PER_SLOT_V22, W.RENT_MIN_E9_PER_SLOT_V22, W.RENT_MAX_KINK_BPS_V22, W.BAND_MIN_LEG_NOTIONAL_TOKENS_V22, W.BAND_EVICT_MAX_VICTIM_MULTIPLE_V22, W.BAND_EVICT_NOTIONAL_MULTIPLE_V22])
      .toEqual([C.bandMaxBps, C.bandMinEpoch, C.bandMinPinEpochs, C.bandMaxPositions, C.minBandWidthTicks, C.genesisFloorMultiple, C.maxRentE9, C.rentMinE9, C.rentMaxKinkBps, C.bandMinLegTokens, C.bandEvictMaxVictim, C.bandEvictNotional]);
  });
  it("tags and PDA kinds", () => {
    const T = W.IX_TAG_V22;
    expect([T.SettleHoldingRent, T.SweepBandDustLeg, T.EvictAndTradeCpi, T.InitBondTranche, T.BondDeposit, T.BondRequestWithdraw, T.BondExecuteWithdraw, T.InsuranceBackstopDraw, T.RescueDeposit, T.InitInsuranceUnits, T.SetG9FeedAllowlist])
      .toEqual([C.tagSettleRent, C.tagSweep, C.tagEvict, ...C.tagBond, C.tagBackstop, C.tagRescue, C.tagUnits, C.tagG9]);
    const spec = JSON.parse(readFileSync(new URL("../specs/wrapper-tags-v22.json", import.meta.url), "utf8")) as { tags: { name: string; tag: number }[]; gaps: number[] };
    for (const [name, tag] of Object.entries(T)) expect(spec.tags.find((t) => t.name === name)?.tag, name).toBe(tag);
    expect(spec.tags.find((t) => t.name === "RequestRedeemLpShares")?.tag).toBe(76);
    for (const g of [113, 114, 115]) expect(spec.tags.some((t) => t.tag === g), `${g} is reserved`).toBe(false);
  });
  it("every v2.2 error code decodes to the crate's name", () => {
    for (const [name, code] of Object.entries(FX.errors)) expect(PERCOLATOR_ERRORS[code]?.name, `${code}`).toBe(name);
  });
  it("PDAs", () => {
    const program = new PublicKey(new Uint8Array(32).fill(7));
    for (const p of FX.pdas) {
      const market = new PublicKey(p.market), owner = new PublicKey(p.owner);
      expect([W.deriveBondTrancheV22(program, market)[0].toBase58(), W.deriveBondTrancheV22(program, market)[1]]).toEqual([p.tranche, p.tb]);
      expect([W.deriveBondPositionV22(program, market, owner)[0].toBase58(), W.deriveBondPositionV22(program, market, owner)[1]]).toEqual([p.position, p.pb]);
      expect([W.deriveInsuranceUnitsV22(program, market)[0].toBase58(), W.deriveInsuranceUnitsV22(program, market)[1]]).toEqual([p.units, p.ub]);
    }
    expect([W.deriveG9FeedAllowlistV22(program)[0].toBase58(), W.deriveG9FeedAllowlistV22(program)[1]]).toEqual([FX.g9Pda.pda, FX.g9Pda.bump]);
  });
});

describe("LAYOUT_V22 variant B == the real crate (offset_of!)", () => {
  const L = FX.layout;
  it("sizes", () => {
    expect(LAYOUT_V22).toBe(LAYOUT_V22_VARIANT_B);
    expect([LAYOUT_V22.version, LAYOUT_V22.engineDiscriminator, LAYOUT_V22.marketGroupOff, LAYOUT_V22.marketGroupLen, LAYOUT_V22.assetSlotStride, LAYOUT_V22.wrapperSlotLen, LAYOUT_V22.engineSlotLen, LAYOUT_V22.assetStateLen, LAYOUT_V22.portfolio.accountLen, LAYOUT_V22.portfolio.legStride, LAYOUT_V22.portfolio.matcherConfigOff])
      .toEqual([L.wrapperVersion, L.engineDiscriminator, L.marketGroupOff, L.marketGroupLen, L.assetSlotStride, L.wrapperSlotLen, L.engineSlotLen, L.assetStateLen, L.portfolioAccountLen, L.legStride, L.portfolioMatcherConfigOff - 16]);
    expect([LAYOUT_V22.wrapperSlot.riskLimits, LAYOUT_V22.wrapperSlot.growth, LAYOUT_V22.wrapperSlot.vaultLp, LAYOUT_V22.wrapperSlot.vaultLpDraw]).toEqual([L.riskLimitsSlotOff, L.growthSlotOff, L.vaultLpSlotOff, L.vaultLpDrawSlotOff]);
    expect([LAYOUT_V22.accounts.redemptionBody, LAYOUT_V22.accounts.redemptionExtBody, LAYOUT_V22.accounts.bondTrancheBody, LAYOUT_V22.accounts.bondPositionBody, LAYOUT_V22.accounts.insuranceUnitsBody, LAYOUT_V22.accounts.g9FeedAllowlistBody]).toEqual([L.redemptionBody, L.redemptionExtBody, L.bondTrancheBody, L.bondPositionBody, L.insuranceUnitsBody, L.g9AllowlistBody]);
  });
  it("offsets", () => {
    for (const [k, v] of Object.entries(LAYOUT_V22.group)) { if (k === "maxMarketSlotsInConfig") continue; expect(v, `group.${k}`).toBe(L.group[k]); }
    for (const [k, v] of Object.entries(LAYOUT_V22.assetState)) expect(v, `assetState.${k}`).toBe(L.assetState[k]);
    for (const [k, v] of Object.entries(LAYOUT_V22.engineSlot)) expect(v, `engineSlot.${k}`).toBe(L.engineSlot[k]);
    for (const [k, v] of Object.entries(LAYOUT_V22.portfolio.leg)) expect(v, `leg.${k}`).toBe(L.leg[k]);
    expect(LAYOUT_V22.portfolio.legsOff).toBe(L.portfolio.legs);
    expect(LAYOUT_V22.portfolio.sourceDomainsOff).toBe(L.portfolio.sourceDomains);
    expect(LAYOUT_V22.portfolio.resolvedPayoutReceiptOff).toBe(L.portfolio.resolvedPayoutReceipt);
  });
  it("stage A row keeps the earlier probe (leg 185, portfolio 10,091, slot 2,597) and is NOT the default", () => {
    expect([LAYOUT_V22_STAGE_A.portfolio.legStride, LAYOUT_V22_STAGE_A.portfolio.accountLen, LAYOUT_V22_STAGE_A.assetSlotStride]).toEqual([185, 10091, 2597]);
    expect(LAYOUT_V22_STAGE_A).not.toBe(LAYOUT_V22);
    expect(LAYOUT_V22.status).toBe("PROVISIONAL");
  });
  it("NEGATIVE CONTROL: the v2.1 row disagrees with the crate", () => {
    expect(LAYOUT_V21.assetSlotStride).not.toBe(L.assetSlotStride);
    expect(LAYOUT_V21.portfolio.legStride).not.toBe(L.legStride);
  });
});

describe("account decoders vs the program's own writes", () => {
  const A = FX.accounts;
  const stamp = (b: Uint8Array) => { const v = new DataView(b.buffer); v.setUint16(8, 19, true); return b; };
  // the program stamps VERSION via write_header; fixture bytes already carry it
  it("bond tranche", () => {
    const t = S.decodeBondTrancheV20(unhex(A.bondTranche.hex));
    expect([t.cBAtoms, t.bSharesTotal, t.lastCouponSlot, t.couponBpsPerYear, t.bondCooldownSlots, t.bondCapBpsOfC, t.lastUtilBps, t.couponPaidTotalAtoms, t.bump])
      .toEqual([1_000_000_000_000_000_000_000n, 999_999_999_999_999_999_999n, 777n, 801, 9001, 4999, 1234, 4242n, 250]);
    expect(() => S.decodeBondTrancheV20(unhex(A.bondTrancheBadPad.hex))).toThrow(UnknownLayoutError);
    expect(A.bondTrancheBadPad.programReads).toBe(false);
    expect(S.decodeBondTrancheV20(unhex(A.bondTranche.hex)).marketGroup.toBytes().every((x) => x === 9)).toBe(true);
  });
  it("bond position", () => {
    const p = S.decodeBondPositionV20(unhex(A.bondPosition.hex));
    expect([p.shares, p.pendingWithdrawShares, p.requestSlot, p.bump]).toEqual([123_456_789_012_345_678_901n, 7n, 99n, 251]);
    expect(() => S.decodeBondPositionV20(unhex(A.bondPositionPendingOverShares.hex))).toThrow(UnknownLayoutError);
  });
  it("insurance units (192 B body)", () => {
    const u = S.decodeInsuranceUnitsV20(unhex(A.insuranceUnits.hex));
    expect([u.unitsTotal, u.unitsStake, u.unitsCreator, u.backstopReceivableAtoms, u.snapInsuranceMintAtoms, u.snapInsuranceFreeAtoms, u.snapSlot, u.creatorPaidToStakeAtoms, u.g9PendingSlot, u.g9Epoch, u.g9EpochDrawnAtoms, u.bump])
      .toEqual([30n, 10n, 20n, 1n, 2n, 3n, 4n, 5n, 6n, 7n, 8n, 249]);
    expect(() => S.decodeInsuranceUnitsV20(unhex(A.insuranceUnitsBadTotal.hex))).toThrow(UnknownLayoutError);
    expect(() => S.decodeInsuranceUnitsV20(unhex(A.insuranceUnits.hex).subarray(0, 16 + 160))).toThrow(/too short/);
  });
  it("G9 allowlist", () => {
    const g = S.decodeG9FeedAllowlistV22(unhex(A.g9Allowlist.hex));
    expect([g.count, g.bump, g.keys.length]).toEqual([2, 254, 2]);
    expect(g.keys[1].toBytes()[0]).toBe(2);
    expect(() => S.decodeG9FeedAllowlistV22(unhex(A.g9AllowlistUnlistedSet.hex))).toThrow(UnknownLayoutError);
  });
  it("redemption request, 112 and 128 bytes", () => {
    const legacy = S.decodeLpRedemptionV22(unhex(A.redemptionLegacy.hex));
    expect([legacy.extended, legacy.minPayoutAtoms, legacy.keeperOk, legacy.shares]).toEqual([false, 0n, false, 55n]);
    const v22 = S.decodeLpRedemptionV22(unhex(A.redemptionV22.hex));
    expect([v22.extended, v22.minPayoutAtoms, v22.keeperOk]).toEqual([true, 0x1122334455667788n, true]);
    expect(() => S.decodeLpRedemptionV22(unhex(A.redemptionV22BadKeeper.hex))).toThrow(UnknownLayoutError);
    expect(S.redemptionDataSizesV22()).toEqual([112, 128]);
    expect(unhex(A.redemptionLegacy.hex).length).toBe(112);
    expect(unhex(A.redemptionV22.hex).length).toBe(128);
    void stamp;
  });
});

describe("pure rules == the crate", () => {
  const B = (s: string) => BigInt(s);
  const N = (x: bigint | null) => (x === null ? null : x.toString());
  const fns: Record<string, (i: string[]) => (string | null)[]> = {
    split3: (i) => { const t = M.trancheSplit3V22(B(i[0]), B(i[1]), B(i[2])); return [t.senior, t.bond, t.junior].map(String); },
    impaired: (i) => [String(M.bondImpairedV22(B(i[0]), B(i[1]), B(i[2])))],
    bondShares: (i) => [N(M.bondSharesForDepositV22(B(i[0]), B(i[1]), B(i[2])))],
    bondAtoms: (i) => [N(M.bondAtomsForRedemptionV22(B(i[0]), B(i[1]), B(i[2])))],
    claimAfter: (i) => [N(M.bondClaimAfterRedemptionV22(B(i[0]), B(i[1]), B(i[2])))],
    insTopup: (i) => [N(M.insUnitsForTopupV22(B(i[0]), B(i[1]), B(i[2])))],
    insBurn: (i) => [N(M.insUnitsToBurnV22(B(i[0]), B(i[1]), B(i[2])))],
    insValue: (i) => [N(M.insUnitsValueV22(B(i[0]), B(i[1]), B(i[2])))],
    mintAdm: (i) => [String(M.insMintAdmissibleV22(B(i[0]), B(i[1]), B(i[2]), B(i[3])))],
    coupon: (i) => [N(M.couponDueV22(B(i[0]), Number(i[1]), B(i[2])))],
    couponSplit: (i) => M.bondCouponSplitV22(B(i[0]), B(i[1])).map(String),
    parAtoms: (i) => [N(M.parAtomsV22(B(i[0]), B(i[1]), B(i[2])))],
    dip: (i) => [String(M.dipFloorOkV22(B(i[0]), B(i[1])))],
    rescueShares: (i) => [N(M.rescueSharesV22(B(i[0]), B(i[1]), B(i[2])))],
    rescueDelta: (i) => [N(M.rescueClaimDeltaV22(B(i[0]), B(i[1]), B(i[2])))],
    backstop: (i) => [String(M.backstopDrawAmountV22(B(i[0]), B(i[1]), B(i[2]), B(i[3]), 5000))],
    epochRoom: (i) => [String(M.g9EpochRoomV22(B(i[0]), B(i[1]), 2000))],
    rescueAdmitted: (i) => [M.rescueAdmittedV22(B(i[0]), B(i[1]), B(i[2]), B(i[3])) ?? "Ok"],
    g9Delay: (i) => [String(M.g9DelayElapsedV22(B(i[0]), B(i[1])))],
    g9Open: (i) => [String(M.g9ProposalOpenV22(B(i[0]), B(i[1])))],
    cooldown: (i) => [String(M.bondCooldownElapsedV22(B(i[0]), B(i[1]), Number(i[2])))],
    capOk: (i) => [String(M.bondCapOkV22(B(i[0]), B(i[1]), B(i[2]), Number(i[3])))],
    lockOk: (i) => [String(M.bondWithdrawLockOkV22(i[0] === null ? null : B(i[0]), B(i[1]), B(i[2]), B(i[3])))],
    utilBps: (i) => [String(M.bondUtilBpsV22(B(i[0]), B(i[1])))],
    valueWorse: (i) => [String(M.vaultValueWorseV22(B(i[0]), B(i[1]), B(i[2])))],
    bandMinWide: (i) => [N(M.bandMinWideAnchorV22(Number(i[0])))],
    bandBounds: (i) => (M.bandBoundsV22(B(i[0]), Number(i[1])) ?? []).map(String),
    bandGenesis: (i) => [String(M.bandGenesisPriceOkV22(B(i[0]), Number(i[1])))],
    refreshWeight: (i) => [String(M.refreshWeightV22(Number(i[0])))],
  };
  const seen = new Set<string>();
  it("every row", () => {
    expect(FX.rules.length).toBeGreaterThan(250);
    for (const r of FX.rules) {
      seen.add(r.fn);
      expect(fns[r.fn], `no SDK mapping for ${r.fn}`).toBeDefined();
      expect(fns[r.fn](r.in), `${r.fn}(${r.in.join(",")})`).toEqual(r.out);
    }
    expect([...seen].sort()).toEqual(Object.keys(fns).sort());
  });
  it("NEGATIVE CONTROL: a wrong rule would fail (swap two inputs)", () => {
    expect(fns.bondShares(["1000", "3000", "4000"])).not.toEqual(fns.bondShares(["1000", "4000", "3000"]));
    const row = FX.rules.find((r) => r.fn === "bondShares" && r.in.join() === "1000,5000,4000")!;
    expect(fns.bondShares(row.in)).toEqual(row.out);
    expect(fns.bondShares(["1000", "4000", "5000"])).not.toEqual(row.out);
  });
});
