/**
 * P2b Earn as counterparty — wrapper tag 103 `VaultLpAllocate`, the tag-99 dials trailer, the
 * `VaultLpExtV19` record, the ext account tails, the Q2 senior floor, and the entry-par vs
 * exit-E3 pricing of a non-bound Earn vault.
 *
 * Source: percolator-prog PR #526 (`feat/p2b-earn-allocation`) at `d9e3e2d7`, stacked on
 * `integration/p2b-merged` `48d9d4ac` (#525 lock exits) and `integration/v19-e1-growth`
 * (#524 growth). Engine `feat/p2b-lock-exits` `1c053113`. DRAFT: not deployed. Every wire byte,
 * offset and rule here is round-tripped through the REAL crate by `test/p2b-earn.test.ts`
 * (fixture `test/fixtures/p2b-parity.json`, generated by `scripts/p2b-parity/`).
 *
 * @module p2b-earn
 */
import { concatBytes, encPubkey, encU8, encU16, encU32, encU64, encU128 } from "./encode.js";
import type { AccountSpec } from "./accounts.js";
import type { PublicKey } from "@solana/web3.js";

// ============================================================================
// Constants (all equal to the wrapper's; pinned by the parity fixture)
// ============================================================================

/** Instruction tags this module adds. 104/105 live in `p2b-lock-exits`. */
export const IX_TAG_P2B_EARN = Object.freeze({ VaultLpAllocate: 103 } as const);

/** `constants::KIND_VAULT_LP_EXT`: the account kind byte (header byte 10) of a `VaultLpExtV19`. */
export const KIND_VAULT_LP_EXT_P2B = 10;
/** `size_of::<VaultLpExtV19>()`. The account is `HEADER_LEN (16) + 128 = 144` bytes. */
export const VAULT_LP_EXT_BODY_LEN_P2B = 128;
/** `state::vault_lp_ext_account_len()`. */
export const VAULT_LP_EXT_ACCOUNT_LEN_P2B = 16 + VAULT_LP_EXT_BODY_LEN_P2B;
/** `constants::VAULT_LP_EXT_VERSION`. */
export const VAULT_LP_EXT_VERSION_P2B = 1;
/** `constants::VAULT_LP_EXT_SEED`: the PDA is `["vault_lp_ext", market]`. */
export const VAULT_LP_EXT_SEED_P2B = "vault_lp_ext";
/**
 * Account offset of `LpVaultRegistryV16._reserved[1]` (16 + 144 + 1): 1 once the market's ext
 * exists. From then on tags 98, 97 and 78 REQUIRE the ext account (fail closed).
 */
export const LP_VAULT_REGISTRY_EXT_FLAG_OFF_P2B = 161;

/** `vault_lp_v18::ALLOC_ALPHA_DEFAULT_BPS` / `ALLOC_ALPHA_MAX_BPS` (hard maximum until L3). */
export const ALLOC_ALPHA_DEFAULT_BPS_P2B = 5_000;
export const ALLOC_ALPHA_MAX_BPS_P2B = 5_000;
/** `vault_lp_v18::ALLOC_BUFFER_DEFAULT_BPS` / `ALLOC_BUFFER_MIN_BPS`. */
export const ALLOC_BUFFER_DEFAULT_BPS_P2B = 3_000;
export const ALLOC_BUFFER_MIN_BPS_P2B = 3_000;
/** `vault_lp_v18::ALLOC_MIN_JUNIOR_BPS` (L-3): tag 103 needs a junior of at least 5% of C_eff. */
export const ALLOC_MIN_JUNIOR_BPS_P2B = 500;
/** `AssetVaultLpV18::p2b_flags` bit 0: creator fees not vested (cushion below target). */
export const ASSET_VAULT_LP_P2B_CREATOR_FEE_VESTING_P2B = 1;
/** `engine BOUND_SCALE`: backing `_num` fields are in 1e-12 atoms. */
export const BOUND_SCALE_P2B = 1_000_000_000_000n;

const U16 = 0xffff;
const U64 = (1n << 64n) - 1n;
const U128 = (1n << 128n) - 1n;
const BPS = 10_000n;

function int(name: string, v: number, min: number, max: number): void {
  if (!Number.isInteger(v) || v < min || v > max) throw new Error(`${name} must be an integer in ${min}..=${max}, got ${v}`);
}
function big(name: string, v: bigint, max: bigint, min = 0n): void {
  if (v < min || v > max) throw new Error(`${name} must be in ${min}..=${max}, got ${v}`);
}

// ============================================================================
// Tag 103 VaultLpAllocate
// ============================================================================

/**
 * VaultLpAllocate (tag 103, permissionless, Live only): `u128 amount`. 17 bytes.
 *
 * Moves `min(amount, alpha*C_eff - allocated, drawable - ceil(buffer*C_eff))` of Earn principal
 * from the vault's pots into the bound vault LP's engine capital (the inverse of tag 98). The
 * program CLAMPS `amount`, so a keeper passes {@link U128_MAX_P2B} to mean "as much as the room
 * allows". Refused with Custom 100 (`VaultLpAllocateRefused`) during a draw, when impaired, with
 * an insolvent LP, a junior below 5% of C_eff, or with no room: a keeper treats 100 as "skip".
 *
 * @param amount  Atoms requested (> 0; the program refuses 0 with 100).
 * @returns Instruction data.
 * @example
 * ```ts
 * const data = encodeVaultLpAllocateP2b(U128_MAX_P2B); // [103, ff * 16]
 * ```
 */
export function encodeVaultLpAllocateP2b(amount: bigint): Uint8Array {
  big("amount", amount, U128);
  return concatBytes(encU8(IX_TAG_P2B_EARN.VaultLpAllocate), encU128(amount));
}

/** `u128::MAX`: pass as the tag-103 `amount` to take whatever the program's limit allows. */
export const U128_MAX_P2B = U128;

/**
 * Tag 103 accounts (9). `registry` is writable because the first allocation CREATES the ext and
 * raises the registry flag; `ext` is `["vault_lp_ext", market]` (writable; created with the
 * defaults alpha 50% / buffer 30% / cushion off if it does not exist, the cranker paying rent).
 */
export const ACCOUNTS_VAULT_LP_ALLOCATE_P2B: readonly AccountSpec[] = [
  { name: "cranker", signer: true, writable: true },
  { name: "market", signer: false, writable: true },
  { name: "registry", signer: false, writable: true },
  { name: "vaultLpState", signer: false, writable: true },
  { name: "lpPortfolio", signer: false, writable: true },
  { name: "ledger", signer: false, writable: true },
  { name: "siblingLedger", signer: false, writable: true },
  { name: "vaultLpExt", signer: false, writable: true },
  { name: "systemProgram", signer: false, writable: false },
] as const;

// ============================================================================
// Tag 99 with the dials trailer
// ============================================================================

/** The four allocation / cushion dials carried by tag 99's 8-byte trailer. */
export interface VaultLpDialsP2b {
  /** Allocation fraction of C_eff, bps. `0..=ALLOC_ALPHA_MAX_BPS_P2B` (5000 until L3). */
  allocAlphaBps: number;
  /** Redemption buffer kept liquid, bps. `ALLOC_BUFFER_MIN_BPS_P2B..=10000`. */
  allocBufferBps: number;
  /** G6 cushion target, bps of C_eff. `0..=10000`; zero iff `cushionShareBps` is zero. */
  cushionTargetBps: number;
  /** G6 share of each LP fee leg routed to the cushion, bps. `0..=10000`. */
  cushionShareBps: number;
}

/**
 * Validate the dials with the wrapper's own bounds (`p2b_set_vault_lp_dials`).
 * @param d  Dials.
 * @throws If the program would refuse them (InvalidInstruction).
 * @example
 * ```ts
 * assertVaultLpDialsP2b({ allocAlphaBps: 5000, allocBufferBps: 3000, cushionTargetBps: 0, cushionShareBps: 0 });
 * ```
 */
export function assertVaultLpDialsP2b(d: VaultLpDialsP2b): void {
  int("allocAlphaBps", d.allocAlphaBps, 0, ALLOC_ALPHA_MAX_BPS_P2B);
  int("allocBufferBps", d.allocBufferBps, ALLOC_BUFFER_MIN_BPS_P2B, 10_000);
  int("cushionTargetBps", d.cushionTargetBps, 0, 10_000);
  int("cushionShareBps", d.cushionShareBps, 0, 10_000);
  if ((d.cushionTargetBps === 0) !== (d.cushionShareBps === 0)) {
    throw new Error("cushionTargetBps and cushionShareBps must be both zero or both non-zero");
  }
}

/** Tag 99 base fields (identical to {@link SetVaultLpRiskArgsP3}); repeated so this module stands alone. */
export interface SetVaultLpRiskV19ArgsP2b extends VaultLpDialsP2b {
  assetIndex: number;
  skewSlopeE9: bigint;
  skewMaxE9: bigint;
  levCapQ: bigint;
  levMaxImrBps: number;
  vaultLpMaxLevBps: number;
  approvedMatcherProgram: PublicKey;
}

/**
 * SetVaultLpRisk (tag 99) with the Phase 2b trailing dials: the 73-byte legacy body, then
 * `u16 alloc_alpha_bps, u16 alloc_buffer_bps, u16 cushion_target_bps, u16 cushion_share_bps`.
 * 81 bytes. The wrapper decodes ANY non-empty trailer as the dials form, so a partial trailer is
 * an error on chain; this encoder always writes all four. Upgrade-authority only.
 *
 * @param a  Fields.
 * @returns 81 bytes.
 * @example
 * ```ts
 * const data = encodeSetVaultLpRiskV19P2b({ ...legacy, allocAlphaBps: 5000, allocBufferBps: 3000, cushionTargetBps: 0, cushionShareBps: 0 });
 * ```
 */
export function encodeSetVaultLpRiskV19P2b(a: SetVaultLpRiskV19ArgsP2b): Uint8Array {
  int("assetIndex", a.assetIndex, 0, U16);
  big("skewSlopeE9", a.skewSlopeE9, U64);
  big("skewMaxE9", a.skewMaxE9, U64);
  big("levCapQ", a.levCapQ, U128);
  int("levMaxImrBps", a.levMaxImrBps, 0, 10_000);
  int("vaultLpMaxLevBps", a.vaultLpMaxLevBps, 0, 50_000);
  assertVaultLpDialsP2b(a);
  return concatBytes(
    encU8(99), encU16(a.assetIndex), encU64(a.skewSlopeE9), encU64(a.skewMaxE9), encU128(a.levCapQ),
    encU16(a.levMaxImrBps), encU32(a.vaultLpMaxLevBps), encPubkey(a.approvedMatcherProgram),
    encU16(a.allocAlphaBps), encU16(a.allocBufferBps), encU16(a.cushionTargetBps), encU16(a.cushionShareBps),
  );
}

/**
 * Tag 99 accounts, dials form (6): the base three, then `registry` (w), `vaultLpExt` (w, created on
 * first use) and the system program. The upgrade authority PAYS the ext rent, so it is WRITABLE
 * here (it is read-only in the legacy 3-account form).
 */
export const ACCOUNTS_SET_VAULT_LP_RISK_V19_P2B: readonly AccountSpec[] = [
  { name: "upgradeAuthority", signer: true, writable: true },
  { name: "programData", signer: false, writable: false },
  { name: "market", signer: false, writable: true },
  { name: "registry", signer: false, writable: true },
  { name: "vaultLpExt", signer: false, writable: true },
  { name: "systemProgram", signer: false, writable: false },
] as const;

// ============================================================================
// Ext account tails for tags 98 / 97 / 78
// ============================================================================

/**
 * Index of the ext account in each ext-governed tag, ONCE the registry's ext flag is set:
 * 98 recall `[8]`, 97 junior withdraw `[11]`, bound 78 crank fees `[7]` (then `[8]` the vault LP
 * portfolio). Equal to the number of base accounts of the tag (8 / 11 / 7 with the bound `[6]`).
 */
export const VAULT_LP_EXT_TAIL_INDEX_P2B = Object.freeze({ 97: 11, 98: 8, 78: 7 } as const);

// ============================================================================
// VaultLpExtV19 record
// ============================================================================

/** Offsets inside the 128-byte `VaultLpExtV19` body (rustc `offset_of!`; add 16 for the account). */
export const VAULT_LP_EXT_FIELD_OFF_P2B = Object.freeze({
  marketGroup: 0, allocatedAtoms: 32, cushionAccruedAtoms: 48, allocatedTotalAtoms: 64,
  deallocatedTotalAtoms: 80, allocAlphaBps: 96, allocBufferBps: 98, cushionTargetBps: 100,
  cushionShareBps: 102, version: 104, bump: 105, padding: 106, reserved: 112,
} as const);

// ============================================================================
// Q2 senior floor: 16-bit ceiling float at AssetRiskLimitsV17 record bytes 42..44
// ============================================================================

/** Record offset (inside the 64-byte `AssetRiskLimitsV17`) of `p2b_senior_floor_code` (u16 LE). */
export const P2B_SENIOR_FLOOR_RECORD_OFF = 42;
/** Asset-slot offset of the code (`ASSET_RISK_LIMITS_OFF 608 + 42`). */
export const P2B_SENIOR_FLOOR_SLOT_OFF = 650;

/**
 * Port of `vault_lp_v18::senior_floor_decode`: `(code & 1023) << (code >> 10)`. The program
 * stores the senior floor `T = C - nav` as a 6-bit exponent / 10-bit mantissa CEILING code, so
 * `decode(encode(v)) >= v` and `<= v*(1 + 2^-9) + 1`. 0 = no floor.
 *
 * @param code  The 16-bit code (record bytes 42..44, little-endian).
 * @returns The floor in atoms.
 * @example
 * ```ts
 * seniorFloorDecodeP2b(1023); // 1023n
 * ```
 */
export function seniorFloorDecodeP2b(code: number): bigint {
  int("code", code, 0, U16);
  return BigInt(code & 1023) << BigInt(code >> 10);
}

/**
 * Port of `vault_lp_v18::senior_floor_encode` (ceiling; saturates to `0xffff` above
 * `1023 * 2^63`). Provided for tests and previews; only the program writes the code.
 *
 * @param v  Floor in atoms.
 * @returns The 16-bit code.
 * @example
 * ```ts
 * seniorFloorEncodeP2b(1025n); // 0x0401 + 1 -> ceiling
 * ```
 */
export function seniorFloorEncodeP2b(v: bigint): number {
  big("v", v, U128);
  if (v === 0n) return 0;
  const bits = BigInt(v.toString(2).length);
  if (bits <= 10n) return Number(v);
  let e = bits - 10n;
  let m = (v >> e) + ((v & ((1n << e) - 1n)) !== 0n ? 1n : 0n);
  if (m === 1024n) {
    e += 1n;
    m = 512n;
  }
  if (e > 63n) return 0xffff;
  return (Number(e) << 10) | Number(m);
}

/**
 * Decode `p2b_senior_floor_code` from one 64-byte `AssetRiskLimitsV17` record and return the floor.
 * @param rec  The 64 record bytes.
 * @returns `{ code, floorAtoms }`; `floorAtoms == 0n` means no floor is armed.
 * @example
 * ```ts
 * const { floorAtoms } = decodeSeniorFloorRecordP2b(rec);
 * ```
 */
export function decodeSeniorFloorRecordP2b(rec: Uint8Array): { code: number; floorAtoms: bigint } {
  if (rec.length !== 64) throw new Error(`AssetRiskLimitsV17 record must be 64 bytes, got ${rec.length}`);
  const code = rec[P2B_SENIOR_FLOOR_RECORD_OFF] | (rec[P2B_SENIOR_FLOOR_RECORD_OFF + 1] << 8);
  return { code, floorAtoms: seniorFloorDecodeP2b(code) };
}

/**
 * Q2 halt rule (`vault_lp_v18::senior_capital_halt`): a risk-increasing vault-LP fill is refused
 * (Custom 103) while its conservative equity after the fill is below the floor.
 * @param lpConservativeEquity  LP equity with no credit for positive PnL.
 * @param floor                 {@link seniorFloorDecodeP2b} of the stored code.
 * @returns True when the fill would be refused.
 * @example
 * ```ts
 * seniorCapitalHaltP2b(99n, 100n); // true
 * ```
 */
export function seniorCapitalHaltP2b(lpConservativeEquity: bigint, floor: bigint): boolean {
  return lpConservativeEquity < floor;
}

// ============================================================================
// Allocation rules (ports of vault_lp_v18)
// ============================================================================

const bpsFloor = (v: bigint, bps: number): bigint => (v * BigInt(bps)) / BPS;
const bpsCeil = (v: bigint, bps: number): bigint => (v * BigInt(bps) + BPS - 1n) / BPS;
const sat = (a: bigint, b: bigint): bigint => (a > b ? a - b : 0n);

/**
 * `vault_lp_v18::vault_lp_alloc_limit`: the most tag 103 may move now,
 * `min(floor(alpha*C_eff) - allocated, drawable - ceil(buffer*C_eff))`, both saturating at 0.
 * `null` on an out-of-range dial (the program then refuses with 100).
 *
 * @param cEff       Effective senior claim.
 * @param allocated  `VaultLpExtV19.allocated_atoms` AFTER the L-2 write-down ({@link allocWrittenDownP2b}).
 * @param drawable   The pots' vault-owned, unreserved fresh backing (both pots).
 * @param alphaBps   Ext alpha.
 * @param bufferBps  Ext buffer.
 * @returns Atoms, or null.
 * @example
 * ```ts
 * vaultLpAllocLimitP2b(1_000n, 0n, 1_000n, 5_000, 3_000); // 500n
 * ```
 */
export function vaultLpAllocLimitP2b(cEff: bigint, allocated: bigint, drawable: bigint, alphaBps: number, bufferBps: number): bigint | null {
  if (alphaBps > ALLOC_ALPHA_MAX_BPS_P2B || bufferBps < ALLOC_BUFFER_MIN_BPS_P2B || bufferBps > 10_000) return null;
  const alphaRoom = sat(bpsFloor(cEff, alphaBps), allocated);
  const liquidRoom = sat(drawable, bpsCeil(cEff, bufferBps));
  return alphaRoom < liquidRoom ? alphaRoom : liquidRoom;
}

/**
 * `vault_lp_v18::vault_lp_alloc_admitted`: tag 103 is refused during a senior draw (outstanding
 * or pending), when impaired (`V < C_eff`), or with an insolvent LP.
 * @param drawOutstanding  `VaultLpStateV18.senior_draw_outstanding_atoms`.
 * @param drawPending      Any pending draw on the asset's draw record.
 * @param vaultValue       V = NAV + H + LP value.
 * @param cEff             Effective senior claim.
 * @param lpEquity         Vault LP certified equity (signed).
 * @returns Admitted?
 * @example
 * ```ts
 * vaultLpAllocAdmittedP2b(0n, false, 1_000n, 1_000n, 0n); // true
 * ```
 */
export function vaultLpAllocAdmittedP2b(drawOutstanding: bigint, drawPending: boolean, vaultValue: bigint, cEff: bigint, lpEquity: bigint): boolean {
  return drawOutstanding === 0n && !drawPending && vaultValue >= cEff && lpEquity >= 0n;
}

/**
 * `vault_lp_v18::alloc_junior_ok` (L-3): `V - C_eff >= ceil(5% * C_eff)`.
 * @param vaultValue  V.
 * @param cEff        Effective senior claim.
 * @returns Whether a first-loss buffer exists.
 * @example
 * ```ts
 * allocJuniorOkP2b(10_500n, 10_000n); // true
 * ```
 */
export function allocJuniorOkP2b(vaultValue: bigint, cEff: bigint): boolean {
  return sat(vaultValue, cEff) >= bpsCeil(cEff, ALLOC_MIN_JUNIOR_BPS_P2B);
}

/**
 * `vault_lp_v18::alloc_written_down` (L-2): the allocation counter is capped at the LP's value.
 * @param allocated  Stored counter.
 * @param lpValue    Vault LP certified equity floored at 0.
 * @returns Counter after the write-down.
 * @example
 * ```ts
 * allocWrittenDownP2b(5_000n, 0n); // 0n
 * ```
 */
export function allocWrittenDownP2b(allocated: bigint, lpValue: bigint): bigint {
  return allocated < lpValue ? allocated : lpValue;
}

/**
 * `vault_lp_v18::vault_lp_dealloc`: the counter after a tag-98 recall of `recalled` atoms.
 * @param allocated  Stored counter.
 * @param recalled   Atoms recalled.
 * @returns Counter, saturating at 0.
 * @example
 * ```ts
 * vaultLpDeallocP2b(500n, 700n); // 0n
 * ```
 */
export function vaultLpDeallocP2b(allocated: bigint, recalled: bigint): bigint {
  return sat(allocated, recalled);
}

/**
 * `vault_lp_v18::vault_lp_alloc_split`: how tag 103 takes `moved` from the two pots, proportional
 * to each pot's drawable backing with the floor on the SMALLER pot. `null` if `moved` exceeds both pots.
 * @param moved   Atoms moved.
 * @param dEven   Even-domain drawable.
 * @param dOdd    Odd-domain drawable.
 * @returns `[takeEven, takeOdd]` or null.
 * @example
 * ```ts
 * vaultLpAllocSplitP2b(100n, 300n, 100n); // [75n, 25n]
 * ```
 */
export function vaultLpAllocSplitP2b(moved: bigint, dEven: bigint, dOdd: bigint): [bigint, bigint] | null {
  const total = dEven + dOdd;
  if (moved > total) return null;
  if (moved === 0n) return [0n, 0n];
  const smallIsOdd = dOdd <= dEven;
  const [dSmall, dLarge] = smallIsOdd ? [dOdd, dEven] : [dEven, dOdd];
  let takeSmall = (moved * dSmall) / total;
  if (takeSmall > dSmall) takeSmall = dSmall;
  const takeLarge = moved - takeSmall;
  if (takeLarge > dLarge) return null;
  return smallIsOdd ? [takeLarge, takeSmall] : [takeSmall, takeLarge];
}

/**
 * `vault_lp_v18::a4_capacity_lock_ok` (code 101 `VaultLpCapacityLocked`): an operation that
 * lowers the vault LP's capital may not leave `N_cap(after) < |LP_eff|`.
 * @param nCapBefore  N_cap before.
 * @param nCapAfter   N_cap after.
 * @param lpEffAbs    |LP effective position|.
 * @returns Allowed?
 * @example
 * ```ts
 * a4CapacityLockOkP2b(10n, 5n, 6n); // false
 * ```
 */
export function a4CapacityLockOkP2b(nCapBefore: bigint, nCapAfter: bigint, lpEffAbs: bigint): boolean {
  return nCapAfter >= nCapBefore || nCapAfter >= lpEffAbs;
}

/**
 * `vault_lp_v18::live_bound_principal_portion` (H-2): a Live bound senior payout's principal
 * portion, `min(payout, available)`. The remainder sits in the vault LP and needs a recall first.
 * @param atomsOut   Payout.
 * @param available  The pots' available principal.
 * @returns Principal portion.
 * @example
 * ```ts
 * liveBoundPrincipalPortionP2b(7_000n, 5_000n); // 5000n
 * ```
 */
export function liveBoundPrincipalPortionP2b(atomsOut: bigint, available: bigint): bigint {
  return atomsOut < available ? atomsOut : available;
}

// ============================================================================
// G6 cushion
// ============================================================================

/**
 * `vault_lp_v18::cushion_split`: split one harvested LP-fee leg into `[senior, cushion]`.
 * @param available          Harvested leg.
 * @param cushionShareBps    Ext share.
 * @param cushionTargetBps   Ext target.
 * @param cEff               Effective senior claim.
 * @param juniorLevel        `V - C_eff` excluding this leg.
 * @returns `[senior, cushion]`, summing to `available`.
 * @example
 * ```ts
 * cushionSplitP2b(1_000n, 5_000, 1_000, 10_000n, 900n); // [900n, 100n]
 * ```
 */
export function cushionSplitP2b(available: bigint, cushionShareBps: number, cushionTargetBps: number, cEff: bigint, juniorLevel: bigint): [bigint, bigint] {
  if (cushionShareBps === 0 || cushionTargetBps === 0) return [available, 0n];
  const need = sat(bpsCeil(cEff, cushionTargetBps), juniorLevel);
  const share = bpsFloor(available, cushionShareBps);
  const cushion = share < need ? share : need;
  return [available - cushion, cushion];
}

/**
 * `vault_lp_v18::cushion_locked`: the cushion tag 97 may not withdraw, `min(accrued, ceil(target*C_eff))`.
 * @param cushionAccrued    `VaultLpExtV19.cushion_accrued_atoms`.
 * @param cEff              Effective senior claim.
 * @param cushionTargetBps  Ext target.
 * @returns Locked atoms.
 * @example
 * ```ts
 * cushionLockedP2b(5_000n, 10_000n, 1_000); // 1000n
 * ```
 */
export function cushionLockedP2b(cushionAccrued: bigint, cEff: bigint, cushionTargetBps: number): bigint {
  const target = bpsCeil(cEff, cushionTargetBps);
  return cushionAccrued < target ? cushionAccrued : target;
}

/**
 * `vault_lp_v18::creator_fee_vested`: creator discretionary fees vest only at or above the
 * cushion target (always, when the cushion is off). Tag 90 returns 102 otherwise.
 * @param juniorLevel       `V - C_eff`.
 * @param cEff              Effective senior claim.
 * @param cushionShareBps   Ext share.
 * @param cushionTargetBps  Ext target.
 * @returns Vested?
 * @example
 * ```ts
 * creatorFeeVestedP2b(999n, 10_000n, 5_000, 1_000); // false
 * ```
 */
export function creatorFeeVestedP2b(juniorLevel: bigint, cEff: bigint, cushionShareBps: number, cushionTargetBps: number): boolean {
  if (cushionShareBps === 0 || cushionTargetBps === 0) return true;
  return juniorLevel >= bpsCeil(cEff, cushionTargetBps);
}

// ============================================================================
// Raw records the non-bound pricing reads (rustc offsets; pinned by the parity fixture)
// ============================================================================

/** `KIND_BACKING_DOMAIN_LEDGER`: header kind of an `["lp_backing_ledger", market, domain]` account. */
export const KIND_BACKING_DOMAIN_LEDGER_P2B = 3;
/** `size_of::<BackingDomainLedgerAccountV16>()`; the account is `16 + 224 = 240` bytes (the program requires EXACTLY this length). */
export const BACKING_DOMAIN_LEDGER_BODY_LEN_P2B = 224;
export const BACKING_DOMAIN_LEDGER_ACCOUNT_LEN_P2B = 16 + BACKING_DOMAIN_LEDGER_BODY_LEN_P2B;
/** Field offsets inside the 224-byte ledger body (add 16 for the account). */
export const BACKING_DOMAIN_LEDGER_FIELD_OFF_P2B = Object.freeze({
  marketGroup: 0, authority: 32, totalPrincipalAtoms: 64, totalDepositedAtoms: 80, totalPrincipalWithdrawnAtoms: 96,
  totalEarningsAtoms: 112, totalEarningsWithdrawnAtoms: 128, lastObservedBucketEarningsAtoms: 144, cumulativeLossAtoms: 160,
  cumulativeRecoveryAtoms: 176, lastObservedUnavailablePrincipalAtoms: 192, domain: 208, padding: 210, marketId: 216,
} as const);
/** `EngineAssetSlotV16Account::source_credit_long` / `_short`, relative to the engine slot start (the backing buckets follow at 963 / 1060). */
export const SOURCE_CREDIT_REL_P2B = Object.freeze({ long: 595, short: 779 } as const);
/** `size_of::<SourceCreditStateV16Account>()`. */
export const SOURCE_CREDIT_LEN_P2B = 184;
/** Field offsets inside one `SourceCreditStateV16Account` (the `_num` fields are u128 in 1e-12 atoms). */
export const SOURCE_CREDIT_FIELD_OFF_P2B = Object.freeze({
  positiveClaimBoundNum: 0, exactPositiveClaimNum: 16, freshReservedBackingNum: 32, spentBackingNum: 48, providerReceivableNum: 64,
  validLienedBackingNum: 80, impairedLienedBackingNum: 96, insuranceCreditReservedNum: 112, validLienedInsuranceNum: 128,
  impairedLienedInsuranceNum: 144, creditRateNum: 160, creditEpoch: 176,
} as const);
/** Field offsets inside one `BackingBucketV16Account` (97 bytes); the bucket starts at engine-slot `963` (long) / `1060` (short). */
export const BACKING_BUCKET_FIELD_OFF_P2B = Object.freeze({
  marketId: 0, freshUnlienedBackingNum: 8, validLienedBackingNum: 24, consumedLienedBackingNum: 40, impairedLienedBackingNum: 56,
  utilizationFeeEarnings: 72, expirySlot: 88, status: 96,
} as const);

// ============================================================================
// Non-bound Earn pricing: entry at PAR, exit at E3
// ============================================================================

/**
 * `vault_lp_v18::pot_physical_net_atoms`: a pot's physical backing net of the claims it owes,
 * `floor((fresh_unliened + valid_liened) / scale) - ceil(max(0, claims - insuranceCover) / scale)`,
 * saturating at 0. Floor on the backing, ceil on the claims: never overstates.
 *
 * @param freshUnlienedNum  `bucket.fresh_unliened_backing_num`.
 * @param validLienedNum    `bucket.valid_liened_backing_num`.
 * @param claimBoundNum     `source.positive_claim_bound_num`.
 * @param insuranceCoverNum {@link insuranceCoverNumP2b}.
 * @param scale             `BOUND_SCALE` (default 1e12).
 * @returns Atoms.
 * @example
 * ```ts
 * potPhysicalNetAtomsP2b(1_180n, 0n, 180n, 0n, 1n); // 1000n
 * ```
 */
export function potPhysicalNetAtomsP2b(
  freshUnlienedNum: bigint, validLienedNum: bigint, claimBoundNum: bigint, insuranceCoverNum: bigint, scale: bigint = BOUND_SCALE_P2B,
): bigint {
  if (scale === 0n) return 0n;
  const held = (freshUnlienedNum + validLienedNum) / scale;
  const uncovered = sat(claimBoundNum, insuranceCoverNum);
  const owed = (uncovered + scale - 1n) / scale;
  return sat(held, owed);
}

/**
 * The part of a source's positive-claim bound that insurance (not the pot) owes:
 * `insurance_credit_reserved_num - (valid_liened_insurance_num + impaired_liened_insurance_num)`, saturating.
 * @param insuranceCreditReservedNum  `source.insurance_credit_reserved_num`.
 * @param validLienedInsuranceNum     `source.valid_liened_insurance_num`.
 * @param impairedLienedInsuranceNum  `source.impaired_liened_insurance_num`.
 * @returns The cover in `_num` units.
 * @example
 * ```ts
 * insuranceCoverNumP2b(180n, 0n, 0n); // 180n
 * ```
 */
export function insuranceCoverNumP2b(insuranceCreditReservedNum: bigint, validLienedInsuranceNum: bigint, impairedLienedInsuranceNum: bigint): bigint {
  return sat(insuranceCreditReservedNum, validLienedInsuranceNum + impairedLienedInsuranceNum);
}

/**
 * E3 (`vault_lp_v18::nonbound_pot_available`): a non-bound pot's EXIT value, `min(ledger
 * principal, physical net of claims)`. Tag 77 prices on this.
 * @param principal    `ledger.total_principal_atoms`.
 * @param physicalNet  {@link potPhysicalNetAtomsP2b}.
 * @returns Atoms.
 * @example
 * ```ts
 * nonboundPotAvailableE3P2b(1_000n, 820n); // 820n
 * ```
 */
export function nonboundPotAvailableE3P2b(principal: bigint, physicalNet: bigint): bigint {
  return principal < physicalNet ? principal : physicalNet;
}

/**
 * H-1 (`vault_lp_v18::nonbound_pot_entry_available`): a non-bound pot's ENTRY value is PAR, the
 * ledger principal. Tag 75 prices on this. It moves only with principal flows, so it is never
 * below the exit reading: every entry-to-exit round trip is non-positive.
 * @param principal  `ledger.total_principal_atoms`.
 * @returns The principal.
 * @example
 * ```ts
 * nonboundPotEntryAvailableP2b(1_000n); // 1000n
 * ```
 */
export function nonboundPotEntryAvailableP2b(principal: bigint): bigint {
  return principal;
}

/** One non-bound pot's inputs for {@link nonboundVaultPricingP2b}. */
export interface NonboundPotP2b {
  /** `ledger.total_principal_atoms` (after the program's own sync). */
  totalPrincipalAtoms: bigint;
  totalEarningsAtoms: bigint;
  totalEarningsWithdrawnAtoms: bigint;
  /** {@link potPhysicalNetAtomsP2b} of the pot's bucket and source. */
  physicalNetAtoms: bigint;
}

/** Result of {@link nonboundVaultPricingP2b}. */
export interface NonboundVaultPricingP2b {
  /** Combined ENTRY NAV (par per pot + LP earnings): what a tag-75 deposit is priced on. */
  entryNavAtoms: bigint;
  /** Combined EXIT NAV (E3 per pot + LP earnings): what a tag-77 redemption is priced on. */
  exitNavAtoms: bigint;
  /** `entryNav - exitNav` (>= 0 always): the par - E3 gap (R3-M1 alert quantity). */
  parMinusE3Atoms: bigint;
  /** The gap as bps of the entry NAV (0 when the entry NAV is 0). */
  parMinusE3Bps: number;
}

function potNav(available: bigint, earnings: bigint, withdrawn: bigint, feeShareBps: number): bigint {
  if (earnings < withdrawn) throw new Error("earnings withdrawn exceeds earnings (the program fails with Custom 25)");
  return available + ((earnings - withdrawn) * BigInt(feeShareBps)) / BPS;
}

/**
 * Port of `lp_vault_combined_nav_rule` for a non-bound vault, both readings at once:
 * `nav = sum over the two pots of (available + floor((earnings - withdrawn) * fee_share / 10000))`
 * where `available` is par (entry) or E3 (exit). Use it to show "entry value vs current exit
 * value" and to monitor the R3-M1 par - E3 gap.
 *
 * @param own          Own-domain pot.
 * @param sibling      Sibling pot.
 * @param feeShareBps  `registry.fee_share_bps` (<= 10000).
 * @returns Entry / exit NAV and their gap.
 * @example
 * ```ts
 * const p = nonboundVaultPricingP2b(own, sib, registry.feeShareBps);
 * if (p.parMinusE3Bps > 100) warn("exit is priced > 1% under entry");
 * ```
 */
export function nonboundVaultPricingP2b(own: NonboundPotP2b, sibling: NonboundPotP2b, feeShareBps: number): NonboundVaultPricingP2b {
  int("feeShareBps", feeShareBps, 0, 10_000);
  let entry = 0n;
  let exit = 0n;
  for (const p of [own, sibling]) {
    entry += potNav(nonboundPotEntryAvailableP2b(p.totalPrincipalAtoms), p.totalEarningsAtoms, p.totalEarningsWithdrawnAtoms, feeShareBps);
    exit += potNav(nonboundPotAvailableE3P2b(p.totalPrincipalAtoms, p.physicalNetAtoms), p.totalEarningsAtoms, p.totalEarningsWithdrawnAtoms, feeShareBps);
  }
  const gap = entry - exit;
  return {
    entryNavAtoms: entry, exitNavAtoms: exit, parMinusE3Atoms: gap,
    parMinusE3Bps: entry === 0n ? 0 : Number((gap * BPS) / entry),
  };
}

/**
 * Engine `lp_shares_for_deposit`: `floor(amount * totalShares / nav)`; 1:1 with no shares.
 * @param amount       Deposit atoms.
 * @param totalShares  Shares outstanding.
 * @param navAtoms     ENTRY NAV ({@link NonboundVaultPricingP2b.entryNavAtoms}).
 * @returns Shares minted (null when the program would refuse: nav 0 with shares, or 0 shares).
 * @example
 * ```ts
 * lpSharesForDepositP2b(1_000n, 10_000n, 10_000n); // 1000n
 * ```
 */
export function lpSharesForDepositP2b(amount: bigint, totalShares: bigint, navAtoms: bigint): bigint | null {
  if (totalShares === 0n) return amount;
  if (navAtoms === 0n) return null;
  const s = (amount * totalShares) / navAtoms;
  return s === 0n ? null : s;
}

/**
 * Engine `lp_atoms_for_redemption`: `floor(shares * nav / totalShares)`.
 * @param shares       Shares redeemed.
 * @param totalShares  Shares outstanding.
 * @param navAtoms     EXIT NAV ({@link NonboundVaultPricingP2b.exitNavAtoms}).
 * @returns Atoms, or null when the program would refuse (no shares, or shares > total).
 * @example
 * ```ts
 * lpAtomsForRedemptionP2b(1_000n, 10_000n, 9_900n); // 990n
 * ```
 */
export function lpAtomsForRedemptionP2b(shares: bigint, totalShares: bigint, navAtoms: bigint): bigint | null {
  if (totalShares === 0n || shares > totalShares) return null;
  return (shares * navAtoms) / totalShares;
}

/** What the app shows a non-bound Earn holder: what the shares cost vs what they exit for now. */
export interface EntryVsExitP2b {
  /** Value of the holder's shares at the ENTRY reading (par). */
  entryValueAtoms: bigint;
  /** Value of the holder's shares at the EXIT reading (E3): what tag 77 would pay now (before the per-pot cap). */
  exitValueAtoms: bigint;
  /** `entryValue - exitValue` (>= 0): the holder's current exit haircut. */
  haircutAtoms: bigint;
  /** The haircut as bps of the entry value. */
  haircutBps: number;
}

/**
 * "Entry price vs current exit value" for `shares` of a non-bound Earn vault.
 *
 * @param shares       The holder's LP shares.
 * @param totalShares  Shares outstanding (registry `total_lp_shares_outstanding`).
 * @param pricing      {@link nonboundVaultPricingP2b} result.
 * @returns Entry value, exit value and the haircut.
 * @example
 * ```ts
 * const v = entryVsExitP2b(myShares, registry.totalLpSharesOutstanding, pricing);
 * // "Worth 1,000.00 at entry price, 992.20 if you exit now"
 * ```
 */
export function entryVsExitP2b(shares: bigint, totalShares: bigint, pricing: NonboundVaultPricingP2b): EntryVsExitP2b {
  const entry = lpAtomsForRedemptionP2b(shares, totalShares, pricing.entryNavAtoms);
  const exit = lpAtomsForRedemptionP2b(shares, totalShares, pricing.exitNavAtoms);
  if (entry === null || exit === null) throw new Error("shares must be <= totalShares and totalShares > 0");
  const haircut = entry - exit;
  return {
    entryValueAtoms: entry, exitValueAtoms: exit, haircutAtoms: haircut,
    haircutBps: entry === 0n ? 0 : Number((haircut * BPS) / entry),
  };
}
