/**
 * P3 vault-owned LP — wrapper tags 94..=102 (additive to SDK 8.0.0).
 *
 * Source of truth: percolator-prog `feat/p3-vault-owned-lp` @
 * `b2b2559e62e08a96b978a2d81a67991c93bc6061` (draft dcccrypto/percolator-prog#518, stacked on
 * P1 `feat/p1-safety-release`). Wire = `ix::Instruction::decode` arms 94..=102; account orders
 * = the `handle_*` bodies. Every encoder is round-tripped through the real Rust decoder by
 * `test/p3.test.ts` (fixture `test/fixtures/p3-parity.json`, generated by
 * `scripts/p3-parity/`).
 *
 * RELAUNCH WRAPPER: P1 + P3 (`b2b2559e`) is the relaunch program. The previous devnet wrapper
 * (v18.2, `6377376a`) rejects 94..=102 (InvalidInstructionData).
 *
 * TAG COLLISION: the deprecated v12.x names `IX_TAG.InitSharedVault(94) … QueueWithdrawal(102)`
 * share these numbers. Those encoders throw (removed instructions); the live meanings are in
 * {@link IX_TAG_P3}. P1's `SetAssetRiskLimits` is 93, so there is no P1/P3 tag overlap.
 *
 * WRITABILITY: where the program's writes depend on an argument (tag 98 `target_domain`,
 * tag 102 `source_domain`), or a ledger may be synced through a helper, both backing ledgers
 * are marked writable. An extra writable flag is harmless; a missing one fails at runtime.
 *
 * @module p3
 */
import { concatBytes, encPubkey, encU8, encU16, encU32, encU64, encU128 } from "./encode.js";
import type { AccountSpec } from "./accounts.js";
import type { PublicKey } from "@solana/web3.js";

/** P3 instruction tags (the live meanings of 94..=102 on a P3 wrapper). */
export const IX_TAG_P3 = Object.freeze({
  InitVaultLp: 94,
  VaultLpSetMatcher: 95,
  DepositJuniorTranche: 96,
  WithdrawJuniorTranche: 97,
  VaultLpRecall: 98,
  SetVaultLpRisk: 99,
  VaultLpConvertPnl: 100,
  VaultLpSettleResolved: 101,
  VaultLpReleaseSurplus: 102,
} as const);

/** `VAULT_LP_MIN_JUNIOR_FLOOR_BPS` / `VAULT_LP_MAX_JUNIOR_FLOOR_BPS`. */
export const VAULT_LP_JUNIOR_FLOOR_BPS_RANGE_P3 = Object.freeze({ min: 1_000, max: 10_000 } as const);
/** `VAULT_LP_MAX_LEV_BPS` (5x). 0 means the 1x default `VAULT_LP_DEFAULT_MAX_LEV_BPS`. */
export const VAULT_LP_MAX_LEV_BPS_P3 = 50_000;
/** `VAULT_LP_DEFAULT_MAX_LEV_BPS` (1x). */
export const VAULT_LP_DEFAULT_MAX_LEV_BPS_P3 = 10_000;

const U16 = 0xffff;
const U32 = 0xffffffff;
const U64 = (1n << 64n) - 1n;
const U128 = (1n << 128n) - 1n;
function int(name: string, v: number, min: number, max: number): void {
  if (!Number.isInteger(v) || v < min || v > max) throw new Error(`${name} must be an integer in ${min}..=${max}, got ${v}`);
}
function big(name: string, v: bigint, max: bigint, min = 0n): void {
  if (v < min || v > max) throw new Error(`${name} must be in ${min}..=${max}, got ${v}`);
}

// ============================================================================
// Encoders
// ============================================================================

/**
 * InitVaultLp (tag 94): `u16 junior_floor_bps` (1000..=10000). 3 bytes.
 *
 * @param juniorFloorBps  Junior floor as bps of the senior claim.
 * @returns Instruction data.
 * @example
 * ```ts
 * const data = encodeInitVaultLpP3(2_000);
 * ```
 */
export function encodeInitVaultLpP3(juniorFloorBps: number): Uint8Array {
  int("juniorFloorBps", juniorFloorBps, VAULT_LP_JUNIOR_FLOOR_BPS_RANGE_P3.min, VAULT_LP_JUNIOR_FLOOR_BPS_RANGE_P3.max);
  return concatBytes(encU8(IX_TAG_P3.InitVaultLp), encU16(juniorFloorBps));
}

/** VaultLpSetMatcher (tag 95) fields, in wire order. */
export interface VaultLpSetMatcherArgsP3 {
  /** Live portfolio matcher sequence (CAS; EngineStale on mismatch). */
  expectedSequence: bigint;
  /** Live asset generation frontier (CAS). */
  assetGenerationFrontier: bigint;
  tradeFeeCapBps: number;
  expirySlot: bigint;
  /** Matcher kind (0 Passive, 1 vAMM, 2 Adaptive on a v2 matcher). */
  kind: number;
  tradingFeeBps: number;
  baseSpreadBps: number;
  maxTotalBps: number;
  impactKBps: number;
  liquidityNotionalE6: bigint;
  /** Must be non-zero (VaultLpMatcherNotApproved otherwise). */
  maxFillAbs: bigint;
  /** Must be non-zero (VaultLpMatcherNotApproved otherwise). */
  maxInventoryAbs: bigint;
  feeToInsuranceBps: number;
  skewSpreadMultBps: number;
}

/**
 * VaultLpSetMatcher (tag 95), upgrade-authority only. 96 bytes:
 * u64 expected_sequence, u64 asset_generation_frontier, u16 trade_fee_cap_bps, u64 expiry_slot,
 * u8 kind, u32 trading_fee_bps, u32 base_spread_bps, u32 max_total_bps, u32 impact_k_bps,
 * u128 liquidity_notional_e6, u128 max_fill_abs, u128 max_inventory_abs,
 * u16 fee_to_insurance_bps, u16 skew_spread_mult_bps.
 *
 * @param a  Fields.
 * @returns Instruction data.
 * @example
 * ```ts
 * const data = encodeVaultLpSetMatcherP3({ expectedSequence: 0n, assetGenerationFrontier: 1n, ... });
 * ```
 */
export function encodeVaultLpSetMatcherP3(a: VaultLpSetMatcherArgsP3): Uint8Array {
  big("expectedSequence", a.expectedSequence, U64);
  big("assetGenerationFrontier", a.assetGenerationFrontier, U64);
  int("tradeFeeCapBps", a.tradeFeeCapBps, 0, U16);
  big("expirySlot", a.expirySlot, U64);
  int("kind", a.kind, 0, 255);
  int("tradingFeeBps", a.tradingFeeBps, 0, U32);
  int("baseSpreadBps", a.baseSpreadBps, 0, U32);
  int("maxTotalBps", a.maxTotalBps, 0, U32);
  int("impactKBps", a.impactKBps, 0, U32);
  big("liquidityNotionalE6", a.liquidityNotionalE6, U128);
  big("maxFillAbs", a.maxFillAbs, U128, 1n);
  big("maxInventoryAbs", a.maxInventoryAbs, U128, 1n);
  int("feeToInsuranceBps", a.feeToInsuranceBps, 0, U16);
  int("skewSpreadMultBps", a.skewSpreadMultBps, 0, U16);
  return concatBytes(
    encU8(IX_TAG_P3.VaultLpSetMatcher), encU64(a.expectedSequence), encU64(a.assetGenerationFrontier),
    encU16(a.tradeFeeCapBps), encU64(a.expirySlot), encU8(a.kind), encU32(a.tradingFeeBps), encU32(a.baseSpreadBps),
    encU32(a.maxTotalBps), encU32(a.impactKBps), encU128(a.liquidityNotionalE6), encU128(a.maxFillAbs),
    encU128(a.maxInventoryAbs), encU16(a.feeToInsuranceBps), encU16(a.skewSpreadMultBps),
  );
}

function amountOnly(tag: number, name: string, amount: bigint): Uint8Array {
  big(name, amount, U128);
  return concatBytes(encU8(tag), encU128(amount));
}

/**
 * DepositJuniorTranche (tag 96): `u128 amount`. 17 bytes.
 * @param amount  Collateral atoms.
 * @returns Instruction data.
 * @example
 * ```ts
 * encodeDepositJuniorTrancheP3(1_000_000n);
 * ```
 */
export function encodeDepositJuniorTrancheP3(amount: bigint): Uint8Array {
  return amountOnly(IX_TAG_P3.DepositJuniorTranche, "amount", amount);
}

/**
 * WithdrawJuniorTranche (tag 97): `u128 amount`. 17 bytes.
 * @param amount  Collateral atoms.
 * @returns Instruction data.
 * @example
 * ```ts
 * encodeWithdrawJuniorTrancheP3(500_000n);
 * ```
 */
export function encodeWithdrawJuniorTrancheP3(amount: bigint): Uint8Array {
  return amountOnly(IX_TAG_P3.WithdrawJuniorTranche, "amount", amount);
}

/**
 * VaultLpRecall (tag 98, permissionless): `u128 amount, u16 target_domain`. 19 bytes.
 * @param amount        Atoms to recall from the vault LP into backing (> 0, <= senior shortfall).
 * @param targetDomain  Backing domain that receives it (the registry domain or its sibling).
 * @returns Instruction data.
 * @example
 * ```ts
 * encodeVaultLpRecallP3(100n, 0);
 * ```
 */
export function encodeVaultLpRecallP3(amount: bigint, targetDomain: number): Uint8Array {
  big("amount", amount, U128);
  int("targetDomain", targetDomain, 0, U16);
  return concatBytes(encU8(IX_TAG_P3.VaultLpRecall), encU128(amount), encU16(targetDomain));
}

/** SetVaultLpRisk (tag 99) fields, in wire order. */
export interface SetVaultLpRiskArgsP3 {
  assetIndex: number;
  /** e9 per slot at 100% imbalance; 0 = skew funding off. */
  skewSlopeE9: bigint;
  /** e9 per slot cap; must be <= the market's max_abs_funding_e9_per_slot. */
  skewMaxE9: bigint;
  /** Leverage step-down N_cap in Q; 0 = off. */
  levCapQ: bigint;
  /** <= 10000. */
  levMaxImrBps: number;
  /** <= 50000; 0 = 1x default. */
  vaultLpMaxLevBps: number;
  /** The ONLY matcher program tag 95 accepts for this asset. */
  approvedMatcherProgram: PublicKey;
}

/**
 * SetVaultLpRisk (tag 99), upgrade-authority only. 73 bytes:
 * u16 asset_index, u64 skew_slope_e9, u64 skew_max_e9, u128 lev_cap_q, u16 lev_max_imr_bps,
 * u32 vault_lp_max_lev_bps, [u8;32] approved_matcher_program.
 *
 * @param a  Fields.
 * @returns Instruction data.
 * @example
 * ```ts
 * encodeSetVaultLpRiskP3({ assetIndex: 0, skewSlopeE9: 2000n, skewMaxE9: 900n, levCapQ: 0n, levMaxImrBps: 0, vaultLpMaxLevBps: 0, approvedMatcherProgram: MATCHER });
 * ```
 */
export function encodeSetVaultLpRiskP3(a: SetVaultLpRiskArgsP3): Uint8Array {
  int("assetIndex", a.assetIndex, 0, U16);
  big("skewSlopeE9", a.skewSlopeE9, U64);
  big("skewMaxE9", a.skewMaxE9, U64);
  big("levCapQ", a.levCapQ, U128);
  int("levMaxImrBps", a.levMaxImrBps, 0, 10_000);
  int("vaultLpMaxLevBps", a.vaultLpMaxLevBps, 0, VAULT_LP_MAX_LEV_BPS_P3);
  return concatBytes(
    encU8(IX_TAG_P3.SetVaultLpRisk), encU16(a.assetIndex), encU64(a.skewSlopeE9), encU64(a.skewMaxE9),
    encU128(a.levCapQ), encU16(a.levMaxImrBps), encU32(a.vaultLpMaxLevBps), encPubkey(a.approvedMatcherProgram),
  );
}

/**
 * VaultLpConvertPnl (tag 100, permissionless): `u128 amount`. 17 bytes.
 * @param amount  Atoms of vault-LP PnL to convert to capital.
 * @returns Instruction data.
 * @example
 * ```ts
 * encodeVaultLpConvertPnlP3(1n);
 * ```
 */
export function encodeVaultLpConvertPnlP3(amount: bigint): Uint8Array {
  return amountOnly(IX_TAG_P3.VaultLpConvertPnl, "amount", amount);
}

/**
 * VaultLpSettleResolved (tag 101, permissionless, Resolved): `u8 topup` (0 = close step, 1 = topup claim). 2 bytes.
 * @param topup  0 or 1.
 * @returns Instruction data.
 * @example
 * ```ts
 * encodeVaultLpSettleResolvedP3(0);
 * ```
 */
export function encodeVaultLpSettleResolvedP3(topup: 0 | 1): Uint8Array {
  int("topup", topup, 0, 1);
  return concatBytes(encU8(IX_TAG_P3.VaultLpSettleResolved), encU8(topup));
}

/**
 * VaultLpReleaseSurplus (tag 102, junior owner): `u128 amount, u16 source_domain`. 19 bytes.
 * @param amount        Atoms (> 0, <= backing surplus over the senior claim).
 * @param sourceDomain  Backing domain the surplus is taken from.
 * @returns Instruction data.
 * @example
 * ```ts
 * encodeVaultLpReleaseSurplusP3(10n, 1);
 * ```
 */
export function encodeVaultLpReleaseSurplusP3(amount: bigint, sourceDomain: number): Uint8Array {
  big("amount", amount, U128);
  int("sourceDomain", sourceDomain, 0, U16);
  return concatBytes(encU8(IX_TAG_P3.VaultLpReleaseSurplus), encU128(amount), encU16(sourceDomain));
}

// ============================================================================
// Account lists (w = writable, s = signer), verified against the P3 handlers
// ============================================================================

/**
 * Tag 94 InitVaultLp: 8 accounts, path A ONLY. `authority` = the market's marketauth, which
 * becomes the junior owner. The upgrade-authority "path B" (ProgramData + a signing junior at
 * [8]/[9]) is removed from the relaunch P3 by decision and is not supported by this SDK.
 * `lpPortfolio` must be pre-created (program-owned, portfolio length).
 */
export const ACCOUNTS_INIT_VAULT_LP_P3: readonly AccountSpec[] = [
  { name: "authority", signer: true, writable: true },
  { name: "market", signer: false, writable: true },
  { name: "registry", signer: false, writable: true },
  { name: "vaultLpState", signer: false, writable: true },
  { name: "lpPortfolio", signer: false, writable: true },
  { name: "systemProgram", signer: false, writable: false },
  { name: "ledger", signer: false, writable: true },
  { name: "siblingLedger", signer: false, writable: true },
] as const;
/** Tag 95: 8 accounts. `matcherDelegate` = deriveMatcherDelegate(wrapper, market, lp, registry, matcherProgram, matcherCtx). */
export const ACCOUNTS_VAULT_LP_SET_MATCHER_P3: readonly AccountSpec[] = [
  { name: "upgradeAuthority", signer: true, writable: false },
  { name: "programData", signer: false, writable: false },
  { name: "market", signer: false, writable: false },
  { name: "vaultLpState", signer: false, writable: false },
  { name: "lpPortfolio", signer: false, writable: true },
  { name: "matcherProgram", signer: false, writable: false },
  { name: "matcherCtx", signer: false, writable: true },
  { name: "matcherDelegate", signer: false, writable: false },
] as const;
/** Tag 96: 7 accounts. */
export const ACCOUNTS_DEPOSIT_JUNIOR_TRANCHE_P3: readonly AccountSpec[] = [
  { name: "juniorOwner", signer: true, writable: false },
  { name: "market", signer: false, writable: true },
  { name: "vaultLpState", signer: false, writable: true },
  { name: "lpPortfolio", signer: false, writable: true },
  { name: "sourceToken", signer: false, writable: true },
  { name: "vaultToken", signer: false, writable: true },
  { name: "tokenProgram", signer: false, writable: false },
] as const;
/** Tag 97: 11 accounts. */
export const ACCOUNTS_WITHDRAW_JUNIOR_TRANCHE_P3: readonly AccountSpec[] = [
  { name: "juniorOwner", signer: true, writable: false },
  { name: "market", signer: false, writable: true },
  { name: "registry", signer: false, writable: false },
  { name: "vaultLpState", signer: false, writable: true },
  { name: "lpPortfolio", signer: false, writable: true },
  { name: "ledger", signer: false, writable: true },
  { name: "siblingLedger", signer: false, writable: true },
  { name: "destToken", signer: false, writable: true },
  { name: "vaultToken", signer: false, writable: true },
  { name: "vaultAuthority", signer: false, writable: false },
  { name: "tokenProgram", signer: false, writable: false },
] as const;
/** Tag 98: 8 accounts (permissionless; cranker pays rent if the target ledger is created). */
export const ACCOUNTS_VAULT_LP_RECALL_P3: readonly AccountSpec[] = [
  { name: "cranker", signer: true, writable: true },
  { name: "market", signer: false, writable: true },
  { name: "registry", signer: false, writable: false },
  { name: "vaultLpState", signer: false, writable: true },
  { name: "lpPortfolio", signer: false, writable: true },
  { name: "ledger", signer: false, writable: true },
  { name: "siblingLedger", signer: false, writable: true },
  { name: "systemProgram", signer: false, writable: false },
] as const;
/** Tag 99: 3 accounts. */
export const ACCOUNTS_SET_VAULT_LP_RISK_P3: readonly AccountSpec[] = [
  { name: "upgradeAuthority", signer: true, writable: false },
  { name: "programData", signer: false, writable: false },
  { name: "market", signer: false, writable: true },
] as const;
/** Tag 100: 4 accounts (permissionless). */
export const ACCOUNTS_VAULT_LP_CONVERT_PNL_P3: readonly AccountSpec[] = [
  { name: "caller", signer: true, writable: false },
  { name: "market", signer: false, writable: true },
  { name: "vaultLpState", signer: false, writable: false },
  { name: "lpPortfolio", signer: false, writable: true },
] as const;
/** Tag 101: 12 accounts (permissionless, Resolved). `juniorDestToken` must be owned by the junior owner. */
export const ACCOUNTS_VAULT_LP_SETTLE_RESOLVED_P3: readonly AccountSpec[] = [
  { name: "caller", signer: true, writable: true },
  { name: "market", signer: false, writable: true },
  { name: "registry", signer: false, writable: false },
  { name: "vaultLpState", signer: false, writable: true },
  { name: "lpPortfolio", signer: false, writable: true },
  { name: "ledger", signer: false, writable: true },
  { name: "siblingLedger", signer: false, writable: true },
  { name: "juniorDestToken", signer: false, writable: true },
  { name: "vaultToken", signer: false, writable: true },
  { name: "vaultAuthority", signer: false, writable: false },
  { name: "tokenProgram", signer: false, writable: false },
  { name: "systemProgram", signer: false, writable: false },
] as const;
/** Tag 102: 7 accounts (Live). In Resolved mode append {@link ACCOUNTS_VAULT_LP_RELEASE_SURPLUS_RESOLVED_TAIL_P3}. */
export const ACCOUNTS_VAULT_LP_RELEASE_SURPLUS_P3: readonly AccountSpec[] = [
  { name: "juniorOwner", signer: true, writable: false },
  { name: "market", signer: false, writable: true },
  { name: "registry", signer: false, writable: false },
  { name: "vaultLpState", signer: false, writable: true },
  { name: "lpPortfolio", signer: false, writable: true },
  { name: "ledger", signer: false, writable: true },
  { name: "siblingLedger", signer: false, writable: true },
] as const;
/** Tag 102 Resolved-mode tail: [7] junior dest token (w), [8] vault token (w), [9] vault authority, [10] token program. */
export const ACCOUNTS_VAULT_LP_RELEASE_SURPLUS_RESOLVED_TAIL_P3: readonly AccountSpec[] = [
  { name: "juniorDestToken", signer: false, writable: true },
  { name: "vaultToken", signer: false, writable: true },
  { name: "vaultAuthority", signer: false, writable: false },
  { name: "tokenProgram", signer: false, writable: false },
] as const;
